name: Build release bundles

on:
    workflow_dispatch:

jobs:
    build_libvips_and_imgproxy:
        strategy:
            matrix:
                platform:
                    - arch: amd64
                      runner: ubuntu-latest
                    - arch: arm64
                      runner: ubuntu-24.04-arm
        runs-on: ${{ matrix.platform.runner }}
        steps:
            - name: Check out repo
              uses: actions/checkout@v4

            - name: Cache libvips binaries
              id: cache-libvips
              uses: actions/cache@v4
              with:
                  path: ci/libvips/libvips_bin
                  key: libvips-${{ matrix.platform.arch }}-${{ hashFiles('ci/libvips/versions.properties') }}

            - name: Build libvips
              if: steps.cache-libvips.outputs.cache-hit != 'true'
              working-directory: ci/libvips
              run: ./build.sh

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 'stable'

            - name: Build imgproxy
              run: ./ci/build_imgproxy.sh

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: "imgproxy-libvips-${{ matrix.platform.arch }}"
                  path: imgproxy_build/out

    build_release_bundles:
        runs-on: ubuntu-latest
        needs:
            - build_libvips_and_imgproxy
        steps:
            - name: Check out repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Build Smithereen
              run: mvn package -Dmaven.test.skip=true

            - name: Download imgproxy and libvips
              uses: actions/download-artifact@v4
              with:
                  pattern: "imgproxy-libvips-*"

            - name: Prepare release bundles
              run: ./ci/prepare_bundles.sh

            - name: Upload release bundles
              uses: actions/upload-artifact@v4
              with:
                  name: "bundles"
                  path: smithereen-bundle-*.tar.gz
