name: Build release bundles

on:
    workflow_dispatch:

jobs:
    build_imgproxy:
        strategy:
            matrix:
                platform:
                    - arch: amd64
                      runner: ubuntu-latest
                    - arch: arm64
                      runner: ubuntu-24.04-arm
        runs-on: ${{ matrix.platform.runner }}
        steps:
            - name: Check out repo
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 'stable'

            - name: Build imgproxy
              run: ./ci/build_imgproxy.sh

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: "imgproxy-libvips-${{ matrix.platform.arch }}"
                  path: imgproxy_build/out

    build_release_bundles:
        runs-on: ubuntu-latest
        needs:
            - build_imgproxy
        steps:
            - name: Check out repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Build Smithereen
              run: mvn package -Dmaven.test.skip=true

            - name: Download imgproxy and libvips
              uses: actions/download-artifact@v4
              with:
                  pattern: "imgproxy-libvips-*.zip"

            - name: Prepare release bundles
              run: ./ci/prepare_bundles.sh

            - name: Upload release bundle x86_64
              uses: actions/upload-artifact@v4
              with:
                  name: "smithereen-bundle-x86_64"
                  path: bundles/amd64

            - name: Upload release bundle arm64
              uses: actions/upload-artifact@v4
              with:
                  name: "smithereen-bundle-arm64"
                  path: bundles/arm64
